name: ci

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Visual Component tests (App) ðŸ§ª
        uses: cypress-io/github-action@v2
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
        with:
          command: npm run cvt

      - name: Run Component tests, but visual (App) ðŸ§ª
        uses: cypress-io/github-action@v2
        with:
          install: false
          command: npm run ct

      - name: Run E2E tests ðŸ§ª
        uses: cypress-io/github-action@v2
        with:
          install: false
          command: npm run e2e:ci
